# Generated by Django 5.0.1 on 2024-01-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='plant_image')),
                ('description', models.CharField(max_length=1000)),
                ('Mostly_caused_disease_name', models.CharField(max_length=255)),
                ('diesease_image', models.ImageField(upload_to='disease_image')),
                ('solution', models.CharField(max_length=255)),
            ],
        ),
    ]
