# Generated by Django 5.0.1 on 2024-01-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userplant_usersuggestion_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='diesease_image',
            new_name='disease_image',
        ),
    ]
