# Generated by Django 5.0.1 on 2024-01-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usersuggestion_likes_alter_mark_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='daily_updates')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
